name:                icfpc2018
version:             0.1.0.0
github:              "nobsun/icfpc2018"
license:             BSD3
author:              "Team Sampou"
maintainer:          "nobsun@gmail.com"
copyright:           "Copyright: (c) 2018 Team Sampou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/icfpc2018#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- mtl
- extra
- mtl
- cereal

library:
  source-dirs: src

# ghc-options:
# - -Wall

executables:
  icfpc2018-exe:         &icfpc2018-exe
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2018

  oga-exe:
    <<:                  *icfpc2018-exe
    main:                Main.hs
    source-dirs:         oga

  oga-traces:
    main:                oga-traces.hs
    source-dirs:         app-traces
    ghc-options:
    - -Wall
    dependencies:
    - icfpc2018

tests:
  icfpc2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2018
    - hspec >= 2.5 && < 3
